databases:
  - name: tiktok-db
    plan: free

services:
  - type: web
    name: tiktok-creator-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-db
          property: connectionString
